---
- name:  install and start apache
  hosts: webservers
  remote_user: ec2-user
  become: yes

  tasks:
  - name: install epel repo
    command: "yum install http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

  - name: install python bindings for SELinux
    yum: name={{item}} state=present
    with_items:
    - libselinux-python
    - libsemanage-python

  - name: test to see if SeLinux is running
    commnand: getenforce
    register: sestatus
    change_when: false

  - name: install apache
  	yum: name=httpd state=present

  - name: start apache
  	service: name=httpd state=started enabled=yes