---
- name: Create a virtual machine on given ESXi hostname
  vmware_guest:
    hostname: "{{ vc_hostname }}"
    username: "{{ vc_username }}"
    password: "{{ vc_password }}"
    datacenter: "{{ vc_datacenter }}"
    validate_certs: no
    folder: /vm/
    name: "{{ vc_vm_name }}"
    state: poweredon
    guest_id: centos64Guest
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    #esxi_hostname: 172.17.0.2
    disk:
    - size_gb: 10
      type: thin
      datastore: "{{ vc_datastore }}"
    hardware:
      memory_mb: 512
      num_cpus: 4
      scsi: paravirtual
    networks:
    - name: VM Network
      mac: aa:bb:dd:aa:00:14
      ip: 10.10.10.100
      netmask: 255.255.255.0
      device_type: vmxnet3
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy_vm
