---
- name: install and start apache and tree
  hosts: all
  remote_user: ec2-user
  become: yes
  serial: 1

  tasks:
  - name: install apache
    yum: name=httpd state=present

  - name: install tree
    yum: name=tree state=present

  - name: waiting for "{{ my_delay }}" seconds...
    wait_for:
      timeout: "{{ my_delay }}"

  #- name: start apache
  #  service: name=httpd state=started enabled=yes
