---
- name: uninstall and start apache and tree
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Removing > apache
    yum: name=httpd state=absent

  - name: Removing > tree
    yum: name=tree state=absent
