---
- name: Check host facts
  hosts: localhost
  tasks:
    - name: dump facts
      debug:
        var: ansible_facts

    - name: This is a {{ ansible_facts.distribution }} system
      command: id
      #DOT NOTATION
      #when: ansible_facts.distribution  == "CentOS"

      #BRACKET NOTATION
      when: ansible_facts['distribution'] == "CentOS"

      #NOTE NOTE NOTE ansible < v2.5 ansible_facts.distribution was preceded by 'ansible_' - ansible_facts.ansible_distribution
