---
- name: Install Apache and starts the service
  hosts: webservers

  tasks:
    - name: Install the required package
      yum:
        name: "{{ ansible_facts['ansible_local']['mycustom']['general']['package'] }}"
        state: latest

    - name: Start the service
      service:
        name: "{{ ansible_facts['ansible_local']['mycustom']['general']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['mycustom']['general']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['mycustom']['general']['enabled'] }}"
