#!/bin/bash
clear
echo -e "\n******************************"
myTowerVersion=`cat /etc/redhat-release |grep "7."`
rhv=7
if [[ -z "$myTowerVersion" ]];
then
  myTowerVersion=`cat /etc/redhat-release |grep "8."`
  rhv=8
fi
echo -e "\ncurrent version: $myTowerVersion"
echo -e "current RHversion: $rhv"
echo -e "\n******************************"
echo -e "\nIs this the correct version?"
read contScript
if [[ "$contScript" = "y" || "$contScript" = "Y" ]];
then
  echo -e "\nDownloading the latest RHEL7 verion of Tower"
  curl -O https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
echo -e "\n******************************"
else
  echo -e "\nAborting operations....."
  exit
fi

   #if [[ "$RMCONF" = "y" || "$RMCONF" = "Y" ]];
   #then
   #ansible-tower-service stop

   #fi

echo -e "\n********************************"
