#!/bin/bash
cd /Users/miltonbrown/Documents/scripts
scp -i "/Users/miltonbrown/Documents/keys/milton.pem" ppush ec2-user@$1:~/
cd -
ssh -i "/Users/miltonbrown/Documents/keys/milton.pem" -l ec2-user $1
