---
- name: install and start apache
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: install apache
    yum: name=httpd state=absent

  - name: install tree
    yum: name=tree state=absent
