---
- name: install and start apache
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: true

  tasks:
  - name: install apache
    yum: name=httpd state=present
    #GOOD SYNTAX:when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'RedHat'

  - name: install tree
    yum: name=tree state=present

  - name: start apache
    service: name=httpd state=started enabled=yes

  - debug: var=got_milk
  #- debug: var=ansible_facts['ansible_os_family']
