---
- name:  initializing windows site
  hosts: winbox

  tasks:
  - name: Install git
    win_chocolatey:
      name: git
      state: absent

  - name: Install notepadplusplus
    win_chocolatey:
      name: notepadplusplus
      state: absent
