---
- name:  initializing windows site
  hosts: winbox

  tasks:
  - name: Install git
    win_chocolatey:
      name: git
      state: absent

  - name: Install notepadplusplus
    win_chocolatey:
      name: notepadplusplus
      state: absent

  - name: Ensure user bob is absent
    win_user:
      name: bob
      state: absent

  - name: Remove a group
    win_group:
      name: mbtestgrp
      state: absent
