---
- name:  install and start apache
  hosts: webservers
  remote_user: ec2-user
  become: yes

  tasks:
  - name: install epel repo and apache
    yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm", state: present }
      - { name: httpd, state: present }

  - name: start apache
    service: name=httpd state=started enabled=yes
