---
- name: apply the common configuration to all hosts
  hosts: all
  remote_user: ec2-user
  become: yes

  roles:
  - common

- name: apply the database configuration
  hosts: dbservers
  remote_user: ec2-user
  become: yes

  roles:
  - mariadb

- name: apply the apache and the web roles
  hosts: webservers
  remote_user: ec2-user
  become: yes

  roles:
  - apache
  - web

- name: apply the lb configuration
  hosts: lbservers
  remote_user: ec2-user
  become: yes

  roles:
  - haproxy 