---
- name:  install and start apache
  hosts: webservers
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Remove repository and apache(and clean up left-over metadata)
    yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: "epel/x86_64", state: absent }
      - { name: httpd, state: absent }
    notify: yum-clean-metadata

  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no
