---
- name:  initializing unsite
  hosts: webservers
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Remove apache
    yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: httpd, state: absent}
      - { name: epel-release-7-11.noarch, state: absent}

  - name: Remove repository(and clean up left-over metadata)
    yum_repository:
      name: epel
      state: absent

    notify: yum-clean-metadata

  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no
