---
- name: Your blank test template
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars_files:
    - /var/lib/awx/projects/_6__my_git/my_playbooks/samples/myvars.yml

  tasks:

    - debug:
        msg: "Serial number: {{ item }}"
      loop:
        - "{{ meraki_network | json_query('[*].serial') }}"
