---
- name: Sample Wait Task adhoc job
  hosts: all
  remote_user: ec2-user
  become: no
  gather_facts: no
  vars:
    idle_timer: 300

  tasks:

  - name: Attempt and graceful roll back demo
    block:
      - wait_for:
          timeout: "{{ idle_timer }}"
      - debug:
          msg: 'I execute normally'
        changed_when: yes
        notify: run me even after an error
      - command: /bin/false
    rescue:
      - wait_for:
          timeout: "{{ idle_timer }}"
      - name: make sure all handlers run
        meta: flush_handlers
        delegate_to: localhost
  handlers:
    - wait_for:
          timeout: "{{ idle_timer }}"
    - name: run me even after an error
      debug:
        msg: 'This handler runs even on error'
      delegate_to: localhost
