---
- name: COMMAND Sample
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:

  - name: Register git version with COMMAND
    command: /bin/git --version
    register: mygitversion
  
  - name: Debug check git version
      debug:
        var: mygitversion.stdout

#- name: Run the command if the specified file does not exist.
#  command: /usr/bin/make_database.sh arg1 arg2
#  args:
#    creates: /path/to/database
#
## You can also use the 'args' form to provide the options.
#- name: This command will change the working directory to somedir/ and will only run when /path/to/database doesn't exist.
#  command: /usr/bin/make_database.sh arg1 arg2
#  args:
#    chdir: somedir/
#    creates: /path/to/database
#
#- name: use argv to send the command as a list.  Be sure to leave command empty
#  command:
#  args:
#    argv:
#      - echo
#      - testing
#
#- name: safely use templated variable to run command. Always use the quote filter to avoid injection issues.
#  command: cat {{ myfile|quote }}
#  register: myoutput
