---
- name: Pinging Playbook
  hosts: all
  environment:
    ANSIBLE_CONFIG: \"/my_special_configs/ansible.cfg\"

  tasks:

    - name: special config ping
      ping:
      environment:
        ANSIBLE_CONFIG: "my_special_configs/ansible.cfg"

