---
- name: Testing Debug Parameters
  hosts: all
  remote_user: ec2-user
  become: yes

  vars:
    machine:
      username: '{{ ansible_user }}'
      password: '{{ ansible_password }}'
    network:
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
    aws:
      access_key: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
      secret_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'
      security_token: '{{ lookup("env", "AWS_SECURITY_TOKEN") }}'
    vmware:
      host: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    gce:
      email: '{{ lookup("env", "GCE_EMAIL") }}'
      project: '{{ lookup("env", "GCE_PROJECT") }}'
    azure:
      client_id: '{{ lookup("env", "AZURE_CLIENT_ID") }}'
      secret: '{{ lookup("env", "AZURE_SECRET") }}'
      tenant: '{{ lookup("env", "AZURE_TENANT") }}'
      subscription_id: '{{ lookup("env", "AZURE_SUBSCRIPTION_ID") }}'

  tasks:
    - debug:
        msg: "<><><><>....Machine Debug....<><><><>"
        var: machine

    - debug:
        msg: "<><><><>....Network Debug....<><><><>"
        var: network

    - debug:
        msg: "<><><><>....AWS Debug....<><><><>"
        var: aws

    - debug:
        msg: "<><><><>....VMWare Debug....<><><><>"
        var: vmware

    - debug:
        msg: "<><><><>....GCE Debug....<><><><>"
        var: gce
    - shell: 'cat {{ gce.pem_file_path }}'
      delegate_to: localhost

    - debug:
        msg: "<><><><>....Azure Debug....<><><><>"
        var: azure
