---
- name: Testing Debug Parameters
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Test echo
    shell: echo "Hello world"
    register: got_milk

  - debug: var=got_milk

  - debug:
      var: got_milk.stdout

  - debug:
      msg: "Testing msg debug --> {{ got_milk }}"
