---
- name: Testing Debug Parameters
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Test echo
    shell: echo "Hello world"
    register: got_milk

  - name: Debug with var equals
    debug: var=got_milk

  - name: Debug with var parameter
    debug:
      var: got_milk

  - name: Debug with var parameter.stdout
    debug:
      var: got_milk.stdout

  - name: Debug with msg parameter
    debug:
      msg: "Testing msg debug --> {{ got_milk }}"

  - name: Debug alternate syntax
    debug: msg="{{ got_milk }}"
