---
- name: Your blank test template
  hosts: all
  remote_user: ec2-user
  become: yes
  gather_facts: no

  tasks:

    - name: Store file into /tmp/fetched/host.example.com/tmp/somefile
      fetch:
        src: /tmp/mytestfile
        dest: /tmp/fetched
