---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    #vm_name: mybox
    vm_name: ""

  tasks:
  - name: sanity check on my variables
    debug:
      msg: "{{ item }}"
    loop:
      - "{{ vm_name }}"
      - "{{ vm_disk_name }}"
      - "{{ vm_vg_name }}"

  - name: find tower variables
    debug:
      msg: "{{ item }}"
    loop:
      - "{{ tower_job_id }}"
      - "{{tower_job_launch_type}}"
      - "{{tower_job_template_id}}"
      - "{{tower_job_template_name}}"
      - "{{tower_user_id}}"
      - "{{tower_user_name}}"
      - "{{tower_user_email}}"
