---
- name: Sample Wait Task adhoc job
  hosts: all
  gather_facts: no
  vars:
    idle_timer: 60

  tasks:

    - name: Sleeping for "{{ idle_timer }}" seconds....Please stand by...
      wait_for:
        timeout: "{{ idle_timer }}"
