---
- name: Pinging Playbook
  hosts: all

  tasks:

    - name: Pinging host
      ping:

    - name: Testing secret var
      shell: ansible-playbook --vault-password-file my_passwd my_secret_inventory
