---
- name: WF template module checker
  hosts: localhost
  #collections:
   # - awx.awx

  tasks:

  - name: Create Workflow Job Templates
    awx.awx.tower_workflow_job_template:
      name: My AutoWF
      description: This is my autowf
      organization: Default
      survey_enabled: yes
      survey: {
            "question_name": "What color is the dog?",
            "question_description": "",
            "required": true,
            "type": "text",
            "variable": "dog_color",
            "min": 0,
            "max": 1024,
            "default": "Black",
            "choices": "",
            "new_question": true
        }
      state: present
      validate_certs: no
    delegate_to: localhost
