---
- name: WF template module checker
  hosts: localhost
  collections:
    - awx.awx

  tasks:

  - name: Create Workflow Job Templates
    ansible.tower.tower_workflow_job_template:
      allow_simultaneous: "{{ item.1.simultaneous }}"
      ask_inventory_on_launch: "{{ item.1.launch_inv }}"
      ask_limit_on_launch: "{{ item.1.launch_limit }}"
      ask_scm_branch_on_launch: no
      ask_variables_on_launch: "{{ item.1.launch_vars }}"
      limit: "{{ item.1.launch_limit }}"
      name: "{{ item.1.name }}"
      description: "{{ item.1.job_desc }}"
      organization: "{{ item.0.name }}"
      inventory: "{{ item.1.inventory }}"
      survey_enabled: "{{ item.1.survey_enabled }}"
      survey: "{{ item.1.survey_spec }}"
      extra_vars: "{{ item.1.extra_vars }}"
      state: present
      tower_host: "{{ bv_tower_host }}"
      tower_oauthtoken: "{{ bv_tower_oauthtoken }}"
      validate_certs: no
    loop: "{{ mgmt_orgs | subelements('workflow_job_templates', skip_missing=True) }}"
