---
- name: Testing Debug Parameters
  hosts: all
  connection: localhost

  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /tmp/mytestfile
      state: touch
      mode: u=rw,g=rw,o=rw
