---
- name: Testing Debug Parameters
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /adumps/mytestfile
      state: file
      mode: u=rw,g=r,o=r
