---
- name: Updating project from playbook
  hosts: all
  remote_user: my_user
  become: yes
  gather_facts: no

  tasks:

  - name: Updating project on Node 1 now...
    uri:
      url: "https://myclusternode1.com/api/v2/projects/9/update/"
      method: "POST"
      user: "admin"
      password: "REDACT"
      force_basic_auth: yes
      headers:
        Content-Type: "application/json"
      body: {}
      body_format: json
      validate_certs: no
      status_code: 202
