---
- name: install and start apache and tree
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: install apache
    yum: name=httpd state=present

  - name: Adding host to Inventory
    uri:
      url: http://ec2-18-188-218-181.us-east-2.compute.amazonaws.com/api/v2/hosts/
      method: POST
      headers:
        Content-Type: "application/json"
      user: admin
      password: kjkiuiKJK88
      return_content: yes
      body: {"name":"44.3.2.1","description":"My box added via uri module","inventory":"3","enabled":"true"}
#        mainlevel:
#          "name": "4.3.2.1",
#          "description": "My box added via uri module",
#          "inventory": 3,
#          "enabled": true,
#          "instance_id": "",
#          "variables": ""
      body_format: json
      status_code: 201
    register: this
