---
- name: install and start apache and tree
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:

  - name: Adding host to Inventory
    uri:
      url: "https://ec2-18-188-218-181.us-east-2.compute.amazonaws.com/api/v2/hosts/"
      method: "POST"
      user: "admin"
      password: "REDACT"
      #force_basic_auth: yes
      headers:
        Content-Type: "application/json"
      return_content: yes
      body: {"name":"44.3.2.1","description":"My box added via uri module","inventory":3,"enabled":"true"}
      body_format: json
      validate_certs: no
      status_code: 201
    #register: this
