---
- name: Pinging Playbook
  hosts: all

  tasks:

  - name: Gather some info from a guest using the vSphere API output schema
    vmware_guest_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter_name }}"
      name: "{{ vm_name }}"
      schema: "vsphere"
      properties: ["config.hardware.memoryMB", "guest.disk", "overallStatus"]
    delegate_to: localhost
    register: info
