---
- name: vmtest playbook
  hosts: all
  gather_facts: no
  roles:
    - { role: community.vmware.vmware_guest_facts }

  tasks:
  
  - name: Gather some info from a guest using the vSphere API output schema
    community.vmware.vmware_guest_facts:
      hostname: "vcenter_server"
      username: "vcenter_use"
      password: "vcenter_pass"
      validate_certs: no
      datacenter: "datacenter_name"
      name: "BOW7XAPPP004"
      schema: "vsphere"
      properties: ["config.hardware.memoryMB", "guest.disk", "overallStatus"]
    delegate_to: localhost
    register: info
