---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Ensure Workflow Template exists
    tower_workflow_template:
      name: AUTOworkflow
      description: A new workflow template
      state: present
      survey_enabled: true
      survey: "{{ lookup('file', '{{ playbook_dir }}/surveys/survey_spec.json') }}"
      tower_username: admin
      tower_password: '{{ twr_password }}'
      tower_host: http://localhost:8052
      tower_verify_ssl: false
