---
- name: Starting playbook
  hosts: all

  tasks:
  - name: Setting facts so that they will be persisted in the fact cache
    set_fact:
      cat_name: cookie
      cacheable: yes

  - name: Win Ping
    win_ping:
