---
- name:  initializing windows site
  hosts: all
  gather_facts: no

  tasks:
  - name: Win Ping
    win_ping:

  - name: Get facts for all virtual machines of a resource group
    azure_rm_virtualmachine_info:
      resource_group: myResourceGroup

