---
- name:  initializing windows site
  hosts: all
  gather_facts: no

  tasks:
  - name: Win Ping
    win_ping:

  - name: Create a private DNS zone
    azure_rm_privatedns:
      resource_group: myResourceGroup
      name: example.com

